CREATE TABLE regions (
                         id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                         world_id UUID NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
                         q INT NOT NULL,
                         r INT NOT NULL,
                         biome TEXT NOT NULL,
                         terrain_type TEXT NOT NULL,
                         climate_type TEXT NOT NULL,
                         owner_civilization_id UUID NULL REFERENCES civilizations(id) ON DELETE SET NULL,
                         population BIGINT NOT NULL DEFAULT 0,
                         stability INT NOT NULL DEFAULT 100,
                         development_level INT NOT NULL DEFAULT 0,
                         pollution INT NOT NULL DEFAULT 0,
                         drought_risk INT NOT NULL DEFAULT 0,
                         revolt_risk INT NOT NULL DEFAULT 0,
                         fire_risk INT NOT NULL DEFAULT 0,
                         seismic_risk INT NOT NULL DEFAULT 0,
                         energy_fragility INT NOT NULL DEFAULT 0,
                         logistic_fragility INT NOT NULL DEFAULT 0,
                         has_capital BOOLEAN NOT NULL DEFAULT FALSE,
                         metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
                         created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                         UNIQUE (world_id, q, r)
);